mosaicmeweb1:
  image: emccode/mosaicme-web
  ports:
    - "0.0.0.0:80:80"
  links:
    - redis
  volumes:
    - /home/emccode/config:/app/config
  env_file: .env

mosaicmecacher1:
  image: emccode/mosaicme-cacher
  links:
    - redis
  env_file: .env

redis:
  image: redis
